package com.naijaswift.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import com.naijaswift.dto.UserRegistrationDTO;
import com.naijaswift.entity.User;

@Mapper(componentModel = "spring")
public interface UserMapper {
     /*** Because it is autogenerated by DB
      * "transactionPin" and "password"  will be ignored cause/.
      *  i would be hashing in the Service class before saving them
     
     ***/
    @Mapping(target = "id",ignore = true)
    @Mapping(target = "password",ignore = true)
    @Mapping(target = "transactionPin",ignore = true)
    @Mapping(target = "wallet",ignore = true)
    User toEntity(UserRegistrationDTO dto);/* Covert dto to entity */

    UserRegistrationDTO toDto(User user);/* convert entity to dto */

}
